import { balanceSchema } from "./balance-model.mjs";
import { stageSchema } from "./stage-schema.mjs";
import { feedbackSchema } from "./feedback-schema.mjs";
import { realtimeSchema } from "./realtime-schema.mjs";
import { barrageSchema } from "./barrage-schema.mjs";
import { entityTypes, idleModes, deathModes } from "./entity-effects.mjs";
const n = (group, label, value, min, max, step = 1, when = "下次事件") => ({
  group,
  label,
  value,
  min,
  max,
  step,
  when,
});
const b = (group, label, value, when = "立即") => ({
  group,
  label,
  value,
  type: "boolean",
  when,
});
const animationSchema = {};
for (const [type, label] of Object.entries(entityTypes)) {
  const group = `怪物动画 · ${label}`;
  const field = (suffix, title, value, min, max, step) => {
    animationSchema[type + suffix] = n(
      group,
      title,
      value,
      min,
      max,
      step,
      "立即",
    );
    animationSchema[type + suffix].entityType = type;
  };
  field("VisualScale", "单怪大小倍率（叠加总体倍率）", 1, 0.2, 4, 0.05);
  animationSchema[type + "IdleMode"] = {
    entityType: type,
    group,
    label: "待机效果",
    type: "select",
    options:
      type === "ultraFast"
        ? { ...idleModes, frames: "序列帧（无额外缩放漂浮）" }
        : idleModes,
    value:
      type === "ultraFast"
        ? "frames"
        : type === "item"
          ? "off"
          : type === "bomb"
            ? "pulse"
            : "breatheFloat",
    when: "立即",
  };
  field(
    "IdleAmount",
    "呼吸/脉动缩放幅度",
    type === "bomb" ? 0.1 : 0.035,
    0,
    0.35,
    0.005,
  );
  field(
    "IdlePeriod",
    "呼吸/脉动周期（秒）",
    type === "bomb" ? 1 : 2.4,
    0.2,
    12,
    0.1,
  );
  if (type === "ultraFast")
    field("AnimationFps", "序列帧播放速度（帧/秒）", 8, 0.5, 30, 0.5);
  field("FloatAmount", "左右漂浮幅度（像素）", 3, 0, 30, 0.5);
  field("FloatPeriod", "左右漂浮周期（秒）", 3.2, 0.2, 12, 0.1);
  field("PulsePower", "脉动节奏曲线（越大越短促）", 4, 1, 12, 0.5);
  animationSchema[type + "DeathMode"] = {
    entityType: type,
    group,
    label: "死亡效果",
    type: "select",
    options: deathModes,
    value: type === "item" ? "off" : "fall",
    when: "立即",
  };
  field("DeathKick", "致命方向击退速度（0关闭击退）", 160, 0, 1200, 10);
  field("DeathGravity", "死亡掉落重力", 900, 10, 4000, 10);
  field("DeathFade", "死亡渐隐时长（秒）", 0.45, 0.05, 5, 0.05);
  field("IdleVariation", "个体节奏差异（周期与幅度）", 0.18, 0, 0.4, 0.01);
  animationSchema[type + "DeathBounceOn"] = {
    ...b(group, "启用尸体碰撞回弹", true),
    entityType: type,
  };
  field("DeathRestitution", "碰撞回弹系数", 0.38, 0, 0.85, 0.01);
  field("DeathFriction", "墙面与落地摩擦", 0.25, 0, 1, 0.01);
  field("DeathRestSpeed", "落稳速度阈值（像素/秒）", 18, 1, 150, 1);
  field("DeathRestHold", "落稳后停留（秒）", 0.12, 0, 3, 0.01);
  field("DeathCollisionScale", "尸体碰撞半径倍率", 1, 0.2, 1.5, 0.01);
}
export const schema = {
  ...realtimeSchema,
  ...barrageSchema,
  ...balanceSchema,
  ...stageSchema,
  ...feedbackSchema,
  upgradeFxOn: b("升级提示与三选一", "启用LEVEL UP入场特效", true),
  upgradeSettleDelay: n(
    "升级提示与三选一",
    "攻击结束后演出收尾（秒）",
    0.35,
    0,
    1.5,
    0.05,
    "下次升级",
  ),
  upgradeIntroDuration: n(
    "升级提示与三选一",
    "特效后显示选项的时长（秒）",
    0.85,
    0,
    3,
    0.05,
    "下次升级",
  ),
  upgradeDim: n(
    "升级提示与三选一",
    "战场压暗透明度",
    0.52,
    0,
    0.9,
    0.01,
    "立即",
  ),
  upgradeFxScale: n(
    "升级提示与三选一",
    "LEVEL UP特效大小",
    1,
    0.6,
    1.6,
    0.05,
    "立即",
  ),
  upgradeSoundOn: b("升级提示与三选一", "启用升级提示音", true),
  upgradeSoundVolume: n(
    "升级提示与三选一",
    "升级提示音相对音量",
    0.75,
    0,
    1,
    0.05,
    "立即",
  ),
  enemyEntryOn: b("怪物入场", "启用上方推进入场", true),
  spawnScatterOn: b("怪物入场", "目的地随机分配到前1至3行", true),
  spawnRow1Weight: n("怪物入场", "第1行落点权重", 55, 0, 100),
  spawnRow2Weight: n("怪物入场", "第2行落点权重", 30, 0, 100),
  spawnRow3Weight: n("怪物入场", "第3行落点权重", 15, 0, 100),
  entryDuration: n("怪物入场", "入场滑动时长（秒）", 0.55, 0.05, 3, 0.05),
  entryStagger: n("怪物入场", "逐只入场间隔（秒）", 0.04, 0, 0.5, 0.01),
  entryJitter: n("怪物入场", "独立入场延迟范围（秒）", 0.08, 0, 0.5, 0.01),
  entryStartCells: n("怪物入场", "起点高于顶墙（格）", 0.8, 0.2, 4, 0.1),
  entryEase: n("怪物入场", "入场减速曲线", 3, 1, 5, 0.1),
  fieldItemsOn: b("战场增益道具", "启用战场增益道具", true),
  pickupChance: n("战场增益道具", "每波生成道具概率", 0.65, 0, 1, 0.05),
  pickupCap: n("战场增益道具", "场上道具数量上限", 3, 1, 12),
  pickupLife: n("战场增益道具", "道具保留回合数", 3, 1, 10),
  pickupDriftOn: b("战场增益道具", "启用 buff 球移动", true),
  pickupDriftMode: {
    ...n("战场增益道具", "buff 球移动方式", "bounce"),
    type: "select",
    options: {
      horizontal: "横向往返 · 碰墙返回",
      bounce: "随机方向 · 四墙反弹",
      local: "出生点附近 · 小范围飘动",
    },
  },
  pickupDriftRange: n(
    "战场增益道具",
    "局部飘动半范围（格）",
    0.4,
    0,
    1.5,
    0.05,
    "立即",
  ),
  pickupDriftSpeedMin: n(
    "战场增益道具",
    "随机移动最低速度（格/秒）",
    0.3,
    0,
    5,
    0.05,
    "立即",
  ),
  pickupDriftSpeedMax: n(
    "战场增益道具",
    "随机移动最高速度（格/秒）",
    0.7,
    0,
    5,
    0.05,
    "立即",
  ),
  pickupTimerOn: b("战场增益道具", "显示道具剩余回合与时钟", true),
  pickupTimerOffsetX: n(
    "战场增益道具",
    "回合标签额外左右偏移",
    0,
    -150,
    150,
    0.5,
    "立即",
  ),
  pickupTimerOffsetY: n(
    "战场增益道具",
    "回合标签额外上下偏移",
    0,
    -150,
    150,
    0.5,
    "立即",
  ),
  pickupMinRow: n("战场增益道具", "生成区域起始行", 4, 1, 20),
  pickupMaxRow: n("战场增益道具", "生成区域结束行", 7, 1, 20),
  pickupRadius: n(
    "战场增益道具",
    "道具碰撞与显示半径（格）",
    0.2,
    0.08,
    0.45,
    0.01,
    "立即",
  ),
  pickupPowerWeight: n("战场增益道具", "狂热晶石生成权重", 25, 0, 100),
  pickupLightningWeight: n("战场增益道具", "雷链晶核生成权重", 25, 0, 100),
  pickupRingWeight: n("战场增益道具", "环刃符生成权重", 25, 0, 100),
  pickupSeedWeight: n("战场增益道具", "爆弹种子生成权重", 25, 0, 100),
  pickupPowerGain: n("战场增益道具", "狂热晶石伤害增幅", 0.6, 0, 3, 0.05),
  pickupLightningHpRatio: n(
    "战场增益道具",
    "雷链追加目标最大HP比例",
    0.15,
    0,
    1,
    0.01,
  ),
  pickupRingHpRatio: n(
    "战场增益道具",
    "环阵命中追加目标最大HP比例",
    0.08,
    0,
    1,
    0.01,
  ),
  pickupSeedHpRatio: n(
    "战场增益道具",
    "种子爆炸追加目标最大HP比例",
    0.25,
    0,
    1,
    0.01,
  ),
  launcherAtkOn: b("发射台 ATK", "显示发射台ATK", true),
  launcherAtkScale: n("发射台 ATK", "ATK标识大小", 1, 0.5, 2, 0.05, "立即"),
  launcherAtkOffsetX: n("发射台 ATK", "ATK横向偏移", 0, -300, 300, 1, "立即"),
  launcherAtkOffsetY: n("发射台 ATK", "ATK纵向偏移", 25, -300, 300, 1, "立即"),
  pickupPowerShots: n(
    "战场增益道具",
    "狂热晶石后续强化出手次数",
    2,
    1,
    20,
    1,
    "下次拾取",
  ),
  powerBadgeOn: b("狂热增伤标识", "显示发射台增伤图标", true),
  powerBadgeScale: n(
    "狂热增伤标识",
    "增伤图标整体大小",
    1,
    0.5,
    2,
    0.05,
    "立即",
  ),
  powerBadgeOffsetX: n(
    "狂热增伤标识",
    "增伤图标横向偏移",
    0,
    -300,
    300,
    1,
    "立即",
  ),
  powerBadgeOffsetY: n(
    "狂热增伤标识",
    "增伤图标纵向偏移",
    -58,
    -300,
    300,
    1,
    "立即",
  ),
  pickupLightningCount: n("战场增益道具", "雷链最多命中怪物数", 6, 1, 30),
  pickupLightningRange: n(
    "战场增益道具",
    "雷链每跳搜索范围（格）",
    3,
    0.5,
    10,
    0.1,
  ),
  pickupLightningDamage: n(
    "战场增益道具",
    "雷链伤害倍率（当前刀伤）",
    2,
    0.1,
    10,
    0.1,
  ),
  pickupLightningDuration: n(
    "战场增益道具",
    "雷链闪光时长（秒）",
    0.45,
    0.05,
    2,
    0.05,
  ),
  pickupRingCount: n("战场增益道具", "环形刀阵飞刀数量", 12, 3, 32),
  pickupRingDamage: n(
    "战场增益道具",
    "环形刀阵伤害倍率（当前刀伤）",
    1.5,
    0.1,
    10,
    0.1,
  ),
  pickupRingPierce: n("战场增益道具", "环形刀阵穿透数", 1, 0, 10),
  pickupRingAngle: n("战场增益道具", "环形刀阵起始角（度）", 0, 0, 360),
  pickupRingCap: n("战场增益道具", "每轮额外环阵飞刀上限", 64, 3, 256),
  pickupSeedDamage: n(
    "战场增益道具",
    "种子爆炸伤害倍率（当前刀伤）",
    5,
    0.1,
    20,
    0.1,
  ),
  pickupSeedDelay: n("战场增益道具", "种子引爆延迟（秒）", 0.8, 0.1, 5, 0.05),
  pickupSeedRadius: n(
    "战场增益道具",
    "种子爆炸波及半径（格）",
    1.3,
    0.1,
    5,
    0.1,
  ),
  knifeMinVisible: n(
    "飞刀插入蒙版",
    "至少露出刀长比例",
    0.2,
    0.05,
    0.8,
    0.01,
    "立即",
  ),
  knifeContactOverlap: n(
    "飞刀插入蒙版",
    "接触重叠补偿",
    0.75,
    0,
    4,
    0.25,
    "立即",
  ),
  knifeLocalMask: b("飞刀插入蒙版", "使用刀身透明蒙版（关闭为旧圆形）", true),
  knifeMaskDepthScale: n(
    "飞刀插入蒙版",
    "刀刃隐藏深度倍率",
    1,
    0,
    3,
    0.05,
    "立即",
  ),
  enemyIdleOn: b("怪物动画 · 总开关", "启用怪物待机动画", true),
  enemyDeathOn: b("怪物动画 · 总开关", "启用怪物死亡动画", true),
  deathVisualCap: n(
    "怪物动画 · 总开关",
    "同时保留死亡动画上限",
    128,
    1,
    512,
    1,
    "立即",
  ),
  ...animationSchema,
  knife3D: b("3D飞刀与统一灯光", "使用3D飞刀（关闭为2D）", false),
  knife3DLightAzimuth: n(
    "3D飞刀与统一灯光",
    "灯光方向角（度）",
    225,
    0,
    360,
    1,
    "立即",
  ),
  knife3DLightElevation: n(
    "3D飞刀与统一灯光",
    "灯光仰角（度）",
    55,
    5,
    90,
    1,
    "立即",
  ),
  knife3DLightIntensity: n(
    "3D飞刀与统一灯光",
    "主灯光强度",
    1.4,
    0,
    4,
    0.05,
    "立即",
  ),
  knife3DAmbient: n(
    "3D飞刀与统一灯光",
    "环境补光强度",
    0.35,
    0,
    2,
    0.05,
    "立即",
  ),
  knife3DRoughness: n(
    "3D飞刀与统一灯光",
    "金属粗糙度",
    0.32,
    0.05,
    1,
    0.01,
    "立即",
  ),
  knife3DMetalness: n("3D飞刀与统一灯光", "金属感", 0.8, 0, 1, 0.05, "立即"),
  knife3DTilt: n(
    "3D飞刀与统一灯光",
    "刀身侧倾角（度）",
    18,
    -70,
    70,
    1,
    "立即",
  ),
  knife3DWidth: n(
    "3D飞刀与统一灯光",
    "3D刀身宽度倍率",
    1,
    0.5,
    2,
    0.05,
    "立即",
  ),
  knife3DThickness: n(
    "3D飞刀与统一灯光",
    "3D刀身厚度倍率",
    1,
    0.2,
    3,
    0.05,
    "立即",
  ),
  knife3DDirections: n(
    "3D飞刀与统一灯光",
    "3D方向缓存数量",
    256,
    64,
    512,
    64,
    "立即",
  ),
  knife3DResolution: n(
    "3D飞刀与统一灯光",
    "3D单刀清晰度",
    96,
    48,
    160,
    16,
    "立即",
  ),
  enemyTypesOn: b(
    "怪物类型",
    "启用普通 / 快速 / 超快速 / 爆炸怪",
    false,
    "下次生成",
  ),
  ultraFastChance: n(
    "怪物类型",
    "超快速鱿鱼怪出现概率（全部模式）",
    0.06,
    0,
    1,
    0.01,
    "下次生成",
  ),
  ultraFastAdvance: n(
    "怪物类型",
    "超快速鱿鱼怪推进倍率",
    3,
    1,
    8,
    1,
    "下次推进",
  ),
  fastChance: n("怪物类型", "快速怪出现概率", 0.2, 0, 1, 0.01, "下次生成"),
  bombChance: n("怪物类型", "爆炸怪出现概率", 0.07, 0, 1, 0.01, "下次生成"),
  fastAdvance: n("怪物类型", "快速怪推进倍率", 2, 1, 5, 1, "下次推进"),
  bombRadius: n("怪物类型", "爆炸半径（格）", 1.5, 0.1, 5, 0.1),
  bombDamage: n("怪物类型", "爆炸波及伤害", 20, 0, 10000, 1),
  bombChain: b("怪物类型", "允许爆炸连锁", true),
  bombSpriteOn: b("炸弹爆炸动画", "叠加爆炸序列帧", true),
  bombSpriteAsset: {
    group: "炸弹爆炸动画",
    label: "爆炸动画素材",
    type: "select",
    options: {
      bombExplosion02: "新增爆炸 · bomb02",
      bombExplosion: "原版爆炸 · bomb-burst",
    },
    value: "bombExplosion02",
    when: "立即",
  },
  bombSpriteScale: n(
    "炸弹爆炸动画",
    "动画大小（相对爆炸直径）",
    1,
    0.1,
    3,
    0.05,
    "立即",
  ),
  bombSpriteFps: n("炸弹爆炸动画", "动画帧率", 16, 1, 60, 1, "立即"),
  bombSpriteOpacity: n("炸弹爆炸动画", "动画不透明度", 1, 0, 1, 0.05, "立即"),
  bombFxDuration: n("怪物类型", "爆炸光圈秒数", 0.4, 0.1, 2, 0.05),
  arenaBoundsVisible: b("背景碰撞框", "显示实际碰撞边界", false),
  aimEnabled: b("瞄准线", "显示瞄准线", true),
  aimAlwaysShow: b("瞄准线", "待发射时常显瞄准线", false),
  aimStyle: {
    group: "瞄准线",
    label: "瞄准线样式",
    type: "select",
    options: { dots: "圆点轨迹", spike: "白蓝光尖刺" },
    value: "dots",
    when: "立即",
  },
  aimSpikeLength: n("瞄准线", "光刺长度", 240, 20, 1500, 1, "立即"),
  aimSpikeWidth: n("瞄准线", "光刺根部宽度", 14, 1, 80, 1, "立即"),
  aimSpikeGlow: n("瞄准线", "光刺发光范围", 12, 0, 60, 1, "立即"),
  aimDotRadius: n("瞄准线", "瞄准点半径", 2, 0.5, 12, 0.5, "立即"),
  aimDotSpacing: n("瞄准线", "瞄准点间距", 0, 0, 100, 1, "立即"),
  aimStartOffset: n("瞄准线", "瞄准线起点留空", 0, 0, 200, 1, "立即"),
  aimMaxLength: n("瞄准线", "瞄准线长度上限", 0, 0, 1500, 1, "立即"),
  aimOpacity: n("瞄准线", "瞄准线不透明度", 1, 0, 1, 0.05, "立即"),
  aimFade: b("瞄准线", "瞄准线末端渐隐", true),
  aimFadePower: n("瞄准线", "瞄准线渐隐曲线", 1, 0.25, 4, 0.05, "立即"),
  hpEnabled: b("怪物 HP 标签", "显示怪物 HP", true),
  hpOffsetX: n("怪物 HP 标签", "HP 标签左右偏移", 0, -150, 150, 0.5, "立即"),
  hpOffsetY: n("怪物 HP 标签", "HP 标签上下偏移", 6.5, -150, 150, 0.5, "立即"),
  hpFollowSize: b("怪物 HP 标签", "HP 位置跟随怪物下沿", true),
  hpFontSize: n("怪物 HP 标签", "HP 数字字号", 11, 6, 48, 0.5, "立即"),
  hpFontBold: b("怪物 HP 标签", "HP 数字加粗", true),
  hpTextOpacity: n("怪物 HP 标签", "HP 数字不透明度", 1, 0, 1, 0.05, "立即"),
  hpTextOffsetX: n("怪物 HP 标签", "HP 数字左右微调", 0, -60, 60, 0.5, "立即"),
  hpTextOffsetY: n(
    "怪物 HP 标签",
    "HP 数字上下微调",
    3.5,
    -60,
    60,
    0.5,
    "立即",
  ),
  hpPlateEnabled: b("怪物 HP 标签", "显示 HP 底板", true),
  hpPlateWidth: n("怪物 HP 标签", "HP 底板宽度", 30, 0, 180, 1, "立即"),
  hpPlateHeight: n("怪物 HP 标签", "HP 底板高度", 17, 0, 100, 1, "立即"),
  hpPlateRadius: n("怪物 HP 标签", "HP 底板圆角", 6, 0, 50, 0.5, "立即"),
  hpPlateOpacity: n("怪物 HP 标签", "HP 底板不透明度", 1, 0, 1, 0.05, "立即"),
  hpPlateAutoWidth: b("怪物 HP 标签", "HP 底板自动适应数字宽度", false),
  hpPlatePadding: n("怪物 HP 标签", "HP 自动底板左右留白", 6, 0, 30, 1, "立即"),
  wallDentEnabled: b("钉墙软体凹陷", "启用钉墙凹陷", true),
  wallDentDepth: n("钉墙软体凹陷", "凹陷深度", 6, 0, 30, 0.5, "立即"),
  wallDentWidth: n("钉墙软体凹陷", "凹陷横向影响范围", 10, 2, 60, 1, "立即"),
  wallDentReach: n("钉墙软体凹陷", "凹陷内部影响深度", 24, 2, 80, 1, "立即"),
  wallDentOffset: n("钉墙软体凹陷", "凹陷沿边偏移", 0, -50, 50, 1, "立即"),
  wallDentDuration: n(
    "钉墙软体凹陷",
    "凹陷压入回弹秒数",
    0.22,
    0,
    1.5,
    0.01,
    "立即",
  ),
  wallDentRebound: n("钉墙软体凹陷", "凹陷回弹幅度", 0.25, 0, 1, 0.05, "立即"),
  stuckKnifeMaskScaleX: n(
    "怪物大小与层级",
    "活怪遮挡横向缩放",
    1,
    0.1,
    3,
    0.05,
    "立即",
  ),
  stuckKnifeMaskScaleY: n(
    "怪物大小与层级",
    "活怪遮挡纵向缩放",
    1,
    0.1,
    3,
    0.05,
    "立即",
  ),
  stuckKnifeMaskOffsetX: n(
    "怪物大小与层级",
    "活怪遮挡左右偏移",
    0,
    -100,
    100,
    1,
    "立即",
  ),
  stuckKnifeMaskOffsetY: n(
    "怪物大小与层级",
    "活怪遮挡上下偏移",
    0,
    -100,
    100,
    1,
    "立即",
  ),
  wallKnifeMaskScaleX: n(
    "怪物大小与层级",
    "钉墙遮挡横向缩放",
    1,
    0.1,
    3,
    0.05,
    "立即",
  ),
  wallKnifeMaskScaleY: n(
    "怪物大小与层级",
    "钉墙遮挡纵向缩放",
    1,
    0.1,
    3,
    0.05,
    "立即",
  ),
  wallKnifeMaskOffsetX: n(
    "怪物大小与层级",
    "钉墙遮挡左右偏移",
    0,
    -100,
    100,
    1,
    "立即",
  ),
  wallKnifeMaskOffsetY: n(
    "怪物大小与层级",
    "钉墙遮挡上下偏移",
    0,
    -100,
    100,
    1,
    "立即",
  ),
  enemyVisualScale: n(
    "怪物大小与层级",
    "怪物显示倍率",
    1,
    0.25,
    3,
    0.05,
    "立即",
  ),
  corpseVisualScale: n(
    "怪物大小与层级",
    "战败怪物额外倍率",
    1,
    0.25,
    3,
    0.05,
    "立即",
  ),
  layerEnemy: n("怪物大小与层级", "活怪层级", 30, 0, 100, 1, "立即"),
  layerCorpse: n("怪物大小与层级", "战败怪物层级", 10, 0, 100, 1, "立即"),
  layerStuckKnife: n("怪物大小与层级", "怪物插刀层级", 40, 0, 100, 1, "立即"),
  layerWallKnife: n("怪物大小与层级", "墙面残刀层级", 20, 0, 100, 1, "立即"),
  layerFlyingKnife: n(
    "怪物大小与层级",
    "飞行与归心刀层级",
    60,
    0,
    100,
    1,
    "立即",
  ),
  stuckKnifeMask: b("怪物大小与层级", "插刀隐藏插入部分", true),
  wallKnifeMaskRatio: n(
    "怪物大小与层级",
    "钉墙圆形遮挡倍率",
    1,
    0,
    1.5,
    0.05,
    "立即",
  ),
  stuckKnifeMaskRatio: n(
    "怪物大小与层级",
    "插刀遮挡范围倍率",
    0.85,
    0,
    1.5,
    0.05,
    "立即",
  ),
  shopEnabled: b("金币商店", "启用金币商店", true),
  shopStartCoins: n("金币商店", "开局金币", 0, 0, 100000, 1, "重开"),
  shopPriceGrowth: n("金币商店", "同项每次涨价倍率", 1.5, 1, 3, 0.05, "立即"),
  shopMaxPurchases: n("金币商店", "每项金币购买上限", 5, 1, 20, 1, "立即"),
  shopDamagePrice: n("金币商店", "锋芒首次价格", 8, 0, 10000, 1, "立即"),
  shopBouncePrice: n("金币商店", "回响首次价格", 12, 0, 10000, 1, "立即"),
  shopPiercePrice: n("金币商店", "破阵首次价格", 12, 0, 10000, 1, "立即"),
  shopSizePrice: n("金币商店", "旋风斩首次价格", 10, 0, 10000, 1, "立即"),
  shopSplitPrice: n("金币商店", "分影首次价格", 16, 0, 10000, 1, "立即"),
  shopPlatformsPrice: n("金币商店", "并锋首次价格", 30, 0, 10000, 1, "立即"),
  shopRecallPrice: n("金币商店", "归心首次价格", 16, 0, 10000, 1, "立即"),
  shopRecallChanceGain: n(
    "金币商店",
    "归心每次概率增量",
    0.02,
    0,
    1,
    0.01,
    "下一刀",
  ),
  discLauncher: b("发射台", "中央圆盘模式（关闭为旧多台模式）", true),
  discAngleStep: n("发射台", "相邻飞刀展开角度（度）", 12, 0, 90, 1, "下一刀"),
  discMaxAngle: n("发射台", "单侧最大展开角度（度）", 80, 0, 180, 1, "下一刀"),
  discKnifeGap: n("发射台", "相邻飞刀横向间隙", 5, 0, 50, 0.5, "下一刀"),
  discTipOffset: n("发射台", "刀尖离圆盘中心距离", 24, 0, 160, 1, "下一刀"),
  launchKnifeOffsetX: n("发射台", "飞刀锚点横向偏移", 0, -300, 300, 1, "立即"),
  launchKnifeOffsetY: n("发射台", "飞刀锚点纵向偏移", 0, -300, 300, 1, "立即"),
  discRadius: n("发射台", "圆盘半径", 19, 8, 60, 1, "立即"),
  discRingWidth: n("发射台", "圆盘边环厚度", 3, 1, 12, 0.5, "立即"),
  discShowOrder: b("发射台", "显示飞刀排列序号", false),
  launchers: n("发射台", "基础飞刀数量（旧模式为台数）", 1, 1, 10, 1, "下一刀"),
  launcherSpread: n("发射台", "发射台分布宽度", 0.8, 0.2, 0.9, 0.05, "下一刀"),
  recallChance: n("万刃归心", "每次出刀触发概率", 0.05, 0, 1, 0.01),
  recallInheritDamage: b("万刃归心", "继承当前飞刀伤害", true, "下次归心"),
  recallInheritSize: b("万刃归心", "继承碰撞大小与旋风斩", true, "下次归心"),
  recallInheritPierce: b("万刃归心", "继承穿透次数", true, "下次归心"),
  recallInheritEnemyBounces: b(
    "万刃归心",
    "继承怪物弹射次数",
    false,
    "下次归心",
  ),
  recallInheritWallBounces: b(
    "万刃归心",
    "继承墙壁反弹次数",
    false,
    "下次归心",
  ),
  recallIntroDuration: n(
    "万刃归心",
    "归心字效前奏秒数",
    0.35,
    0,
    1.5,
    0.01,
    "下次归心",
  ),
  recallShakeDuration: n("万刃归心", "墙刀震动秒数", 0.28, 0, 2, 0.01),
  recallShakeAmount: n("万刃归心", "墙刀震动角度（度）", 8, 0, 35, 0.5),
  recallShakeFrequency: n("万刃归心", "墙刀每秒震动次数", 22, 1, 60),
  recallPullDuration: n("万刃归心", "拔刀动作秒数", 0.06, 0.01, 0.5, 0.01),
  recallPullDistance: n(
    "万刃归心",
    "拔刀向内移动距离",
    24,
    1,
    100,
    1,
    "下次归心",
  ),
  recallHoverDuration: n("万刃归心", "拔刀后瞄准停顿秒数", 0.12, 0, 1, 0.01),
  recallTurnPower: n("万刃归心", "转向曲线指数", 3, 0.25, 6, 0.05, "下次归心"),
  recallStagger: n("万刃归心", "相邻墙刀发射间隔", 0.025, 0, 0.2, 0.005),
  recallStaggerMax: n("万刃归心", "整批错落发射最长秒数", 0.35, 0, 2, 0.05),
  wallEmbed: n("视觉表现", "墙面插入深度", 12, 0, 40, 1, "立即"),
  enemyEmbed: n("视觉表现", "怪物插入深度", 10, 0, 40, 1, "立即"),
  embedDuration: n("视觉表现", "插入动画秒数", 0.12, 0.01, 0.5, 0.01, "立即"),

  launchInset: n("发射台", "发射点距底边/格", 0.65, 0.2, 1.2, 0.05, "下一刀"),
  splitScale: n("飞刀", "分裂刀尺寸继承", 0.75, 0.2, 1, 0.05, "下一刀"),
  carryOffset: n("视觉表现", "带尸距刀尖距离", 10, 0, 50, 1, "立即"),
  pinSag: n("视觉表现", "钉墙尸体下垂", 5, 0, 25, 1, "立即"),
  floatLife: n("视觉表现", "伤害文字秒数", 0.7, 0.2, 2, 0.1, "立即"),
  floatSpeed: n("视觉表现", "伤害文字上浮速度", 35, 0, 100, 1, "立即"),
  cols: n("战场", "列数", 7, 3, 12, 1, "重开"),
  rows: n("战场", "行数", 9, 5, 16, 1, "重开"),
  cell: n("战场", "格子尺寸", 60, 36, 90, 1, "重开"),
  launchX: n("发射台", "发射横向位置", 0.5, 0.1, 0.9, 0.05, "下一刀"),
  lives: n("战场", "初始防线生命", 5, 1, 100, 1, "重开"),
  leakDamage: n("战场", "漏怪扣血", 1, 1, 20),
  seed: n("战场", "随机种子", 221, 1, 999999, 1, "重开"),
  damage: n("飞刀", "基础伤害", 10, 1, 1000, 1, "下一刀"),
  speed: n("飞刀", "发射速度", 660, 80, 1800, 10, "下一刀"),
  radius: n("飞刀", "碰撞半径", 5, 2, 20, 1, "下一刀"),
  knifeLength: n("飞刀", "显示长度", 38, 15, 100, 1, "立即"),
  pierce: n("飞刀", "穿透次数", 0, 0, 30, 1, "下一刀"),
  enemyBounces: n("飞刀", "怪物弹射次数", 0, 0, 30, 1, "下一刀"),
  wallBounces: n("飞刀", "墙壁反弹次数", 0, 0, 30, 1, "下一刀"),
  split: n("飞刀", "命中分裂数量", 0, 0, 5, 1, "下一刀"),
  maxKnives: n("飞刀", "每刀链条总数上限", 32, 1, 128, 1, "下一刀"),
  maxLife: n("飞刀", "最长飞行秒数", 8, 1, 20, 0.5, "下一刀"),
  gravityOn: b("物理实验", "启用重力", false),
  gravityAfterBounces: b("物理实验", "最后一次反弹后启用重力", false),
  gravity: n("物理实验", "重力加速度", 460, 0, 1600, 10, "立即"),
  drag: n("物理实验", "空气阻力", 0.08, 0, 3, 0.02, "立即"),
  restitution: n("物理实验", "碰撞速度保留", 0.88, 0.15, 1, 0.01, "立即"),
  terminalSpeed: n("物理实验", "最大下落速度", 700, 50, 1600, 10, "立即"),
  energyOn: b("动力实验", "启用动力", false),
  energy: n("动力实验", "初始动力", 100, 1, 500, 1, "下一刀"),
  energyDrain: n("动力实验", "每秒动力消耗", 20, 0, 200, 1, "立即"),
  energyCost: n("动力实验", "碰撞动力消耗", 8, 0, 100, 1, "立即"),
  energyGain: n("动力实验", "弹射补充动力", 4, 0, 100, 1, "立即"),
  bounceBoost: n("动力实验", "弹射速度增益", 0, 0, 200, 5, "立即"),
  enemyHp: n("怪物与推进", "基础血量", 10, 1, 500),
  hpGrowth: n("怪物与推进", "每回合血量增长", 1, 0, 30, 0.5),
  enemyRadius: n("怪物与推进", "怪物半径/格", 0.33, 0.15, 0.44, 0.01, "新怪"),
  spawnCount: n("怪物与推进", "每波怪物数量", 1, 0, 12),
  initialRows: n("怪物与推进", "开局怪物行数", 3, 1, 5, 1, "重开"),
  advance: n("怪物与推进", "每次推进格数", 1, 1, 4),
  moveEvery: n("怪物与推进", "每几回合推进", 1, 1, 4),
  moveDuration: n("怪物与推进", "推进动画秒数", 0.4, 0.1, 2, 0.05),
  xpDrop: n("经验与构筑", "每只怪经验", 1, 0, 20),
  xpBase: n("经验与构筑", "首次升级经验", 2, 1, 100),
  xpGrowth: n("经验与构筑", "每级额外经验", 1, 0, 20),
  coinDrop: n("经验与构筑", "每只怪金币", 2, 0, 100),
  killScore: n("经验与构筑", "击杀基础分", 100, 0, 10000),
  comboBonus: n("经验与构筑", "连杀加分", 25, 0, 1000),
  damageUpgrade: n("经验与构筑", "伤害强化幅度", 5, 1, 100),
  sizeUpgrade: n("经验与构筑", "旋风范围每级倍率增量", 0.35, 0.1, 1, 0.05),
  giantWhirlOn: b("旋风斩", "启用最终落点旋风斩", true),
  giantWhirlRadius: n(
    "旋风斩",
    "旋风基础半径（格·乘范围倍率）",
    0.85,
    0.1,
    5,
    0.05,
  ),
  giantWhirlDamage: n("旋风斩", "旋风初级伤害倍率", 1.2, 0, 20, 0.05),
  giantWhirlDamageGain: n("旋风斩", "旋风每级伤害倍率增量", 0.35, 0, 10, 0.05),
  giantWhirlDuration: n("旋风斩", "旋风斩表现时长（秒）", 0.38, 0.1, 2, 0.01),
  giantWhirlOpacity: n("旋风斩", "旋风斩不透明度", 0.85, 0, 1, 0.05, "立即"),
  splitDamage: n("经验与构筑", "分裂刀伤害继承", 0.65, 0.1, 1, 0.05),
  splitAngle: n("经验与构筑", "分裂散射角度", 28, 5, 80),
  upgradeCap: n("经验与构筑", "单技能等级上限", 8, 1, 30),
  pinLife: n("视觉表现", "钉墙残留秒数", 10, 1, 120, 1, "立即"),
  pinCap: n("视觉表现", "钉墙残留上限", 25, 1, 80, 1, "立即"),
  hitFlash: n("视觉表现", "受击闪白秒数", 0.12, 0, 0.5, 0.01, "立即"),
  hitScale: n("视觉表现", "受击挤压幅度", 0.16, 0, 0.4, 0.02, "立即"),
  shake: n("视觉表现", "撞击震动", 5, 0, 20, 1, "立即"),
  shakeTime: n("视觉表现", "震动秒数", 0.15, 0, 0.5, 0.01, "立即"),
  wobble: n("视觉表现", "刀柄颤动幅度", 0.12, 0, 0.5, 0.01, "立即"),
  particleCount: n("视觉表现", "单次粒子数", 12, 0, 40, 1, "立即"),
  particleLife: n("视觉表现", "粒子存活秒数", 0.5, 0.1, 2, 0.1, "立即"),
  trail: n("视觉表现", "拖尾点数", 12, 0, 40, 1, "立即"),
  volume: n("音频总控", "总音量", 0.2, 0, 1, 0.05, "立即"),
  musicOn: b("背景音乐", "启用背景音乐", true),
  musicVolume: n("背景音乐", "音乐相对音量", 0.5, 0, 1, 0.05, "立即"),
  sound: b("音频总控", "启用全部声音", true),
  aimSeconds: n("瞄准线", "轨迹预览秒数", 0.32, 0.05, 3, 0.01, "立即"),
  timeScale: n("视觉表现", "播放速度", 1, 0.25, 3, 0.25, "立即"),
};
export const wallMaskSides = {
  Top: "顶部",
  Right: "右侧",
  Bottom: "底部",
  Left: "左侧",
};
const legacyWallMaskSchema = {};
for (const suffix of ["Ratio", "ScaleX", "ScaleY", "OffsetX", "OffsetY"]) {
  const oldKey = `wallKnifeMask${suffix}`,
    spec = schema[oldKey];
  legacyWallMaskSchema[oldKey] = spec;
  delete schema[oldKey];
  for (const [side, label] of Object.entries(wallMaskSides))
    schema[`wall${side}Mask${suffix}`] = {
      ...spec,
      group: "怪物大小与层级",
      label: spec.label.replace("钉墙", `${label}钉墙`),
    };
}
export const defaults = () =>
  Object.fromEntries(Object.entries(schema).map(([k, v]) => [k, v.value]));
const retiredKeys = new Set([
  ...Object.keys(entityTypes).map((type) => type + "DeathSpin"),
  "aimMin",
  "recallDuration",
  "recallDamage",
  "recallExplosionDamage",
  "recallRadius",
  "explosionFx",
  "shopRecallDamageGrowth",
]);
export function validate(data) {
  if (
    !data ||
    data.schemaVersion !== 1 ||
    !data.config ||
    typeof data.config !== "object" ||
    Array.isArray(data.config)
  )
    throw new Error("配置版本不支持或缺少 config；请导入本游戏导出的 JSON。");
  for (const k of Object.keys(data.config))
    if (
      !retiredKeys.has(k) &&
      !Object.hasOwn(schema, k) &&
      !Object.hasOwn(legacyWallMaskSchema, k)
    )
      throw new Error(`未知参数：${k}`);
  const config = defaults();
  for (const [k, v] of Object.entries(data.config)) {
    if (retiredKeys.has(k)) continue; // Retired experiments migrate without losing valid tuning.
    const s = schema[k] || legacyWallMaskSchema[k];
    if (s.type === "boolean") {
      if (typeof v !== "boolean") throw new Error(`${s.label}必须是开关值`);
    } else if (s.type === "select") {
      if (typeof v !== "string" || !Object.hasOwn(s.options, v))
        throw new Error(`${s.label}选项无效`);
    } else if (
      typeof v !== "number" ||
      !Number.isFinite(v) ||
      v < s.min ||
      v > s.max ||
      (s.step === 1 && !Number.isInteger(v))
    )
      throw new Error(
        `${s.label}须为 ${s.min}～${s.max} 范围内的${s.step === 1 ? "整数" : "数字"}`,
      );
    if (Object.hasOwn(schema, k)) config[k] = v;
  }
  // Only missing per-wall fields inherit the last saved shared values.
  for (const oldKey of Object.keys(legacyWallMaskSchema)) {
    if (!Object.hasOwn(data.config, oldKey)) continue;
    for (const side of Object.keys(wallMaskSides)) {
      const key = oldKey.replace("wallKnifeMask", `wall${side}Mask`);
      if (!Object.hasOwn(data.config, key)) config[key] = data.config[oldKey];
    }
  }
  return {
    config,
    presetName:
      typeof data.presetName === "string"
        ? data.presetName.slice(0, 80)
        : "导入配置",
  };
}
export const exportConfig = (config, presetName = "我的手感预设") =>
  JSON.stringify(
    {
      schemaVersion: 1,
      presetName,
      updatedAt: new Date().toISOString(),
      config: validate({ schemaVersion: 1, config }).config,
    },
    null,
    2,
  );
export const presets = {
  crystal: {
    name: "晶糖战场 · 6列10行 / 三种怪物",
    values: { cols: 6, rows: 10, enemyTypesOn: true },
  },
  basic: {
    name: "原味 · 零反弹",
    values: {
      gravityOn: false,
      energyOn: false,
      pierce: 0,
      enemyBounces: 0,
      wallBounces: 0,
      split: 0,
    },
  },
  bounce: {
    name: "弹射试验",
    values: {
      gravityOn: false,
      energyOn: false,
      pierce: 0,
      enemyBounces: 4,
      wallBounces: 4,
      split: 0,
    },
  },
  gravity: {
    name: "重力试验",
    values: {
      gravityOn: true,
      energyOn: false,
      speed: 660,
      gravity: 460,
      pierce: 1,
      enemyBounces: 2,
      wallBounces: 2,
      split: 0,
    },
  },
  energy: {
    name: "重力 + 动力",
    values: {
      gravityOn: true,
      energyOn: true,
      speed: 660,
      gravity: 460,
      pierce: 1,
      enemyBounces: 3,
      wallBounces: 3,
      split: 0,
    },
  },
};
