import { balanceSchema, curveProfiles } from "./balance-model.mjs";
import { stageBalanceKeys } from "./stage-schema.mjs";
export const skillLabels = {
  levelAtk: "升级ATK · 自然成长",
  damage: "锋芒 · 总伤害",
  size: "旋风斩 · 范围与伤害",
  pierce: "破阵 · 穿透",
  bounce: "回响 · 墙反弹",
  split: "分影 · 分裂数量",
  platforms: "并锋 · 齐射数量",
  recall: "归心锻造 · 触发率%",
};
export const skillFields = {
  levelAtk: ["levelAtkGain", "levelAtkPower"],
  damage: ["damage", "damageUpgrade", "upgradeCap"],
  size: [
    "sizeUpgrade",
    "sizeGrowthPower",
    "giantWhirlOn",
    "giantWhirlRadius",
    "giantWhirlDamage",
    "giantWhirlDamageGain",
    "upgradeCap",
  ],
  pierce: ["pierce", "pierceUpgrade", "upgradeCap"],
  bounce: [
    "enemyBounces",
    "wallBounces",
    "enemyBounceUpgrade",
    "wallBounceUpgrade",
    "upgradeCap",
  ],
  split: ["split", "splitUpgrade", "splitDamage", "maxKnives", "upgradeCap"],
  platforms: ["launchers"],
  recall: [
    "recallChance",
    "shopRecallChanceGain",
    "shopMaxPurchases",
    "recallInheritDamage",
    "recallInheritPierce",
    "recallInheritEnemyBounces",
    "recallInheritWallBounces",
  ],
};
export const pressureFields = [
  "hpAtkCapOn",
  "hpAtkHitCap",
  "enemyHp",
  "hpGrowth",
  "spawnCount",
  "enemyCap",
  "initialRows",
  "advance",
  "moveEvery",
  "enemyTypesOn",
  "ultraFastChance",
  "ultraFastAdvance",
  "fastChance",
  "fastAdvance",
  "bombChance",
  "bombRadius",
  "bombDamage",
  "bombChain",
  "lives",
  "leakDamage",
  "spawnScatterOn",
  "spawnRow1Weight",
  "spawnRow2Weight",
  "spawnRow3Weight",
];
export const economyFields = [
  "coinDrop",
  "killScore",
  "comboBonus",
  "shopEnabled",
  "shopStartCoins",
  "shopPriceGrowth",
  "shopMaxPurchases",
  "shopDamagePrice",
  "shopBouncePrice",
  "shopPiercePrice",
  "shopSizePrice",
  "shopSplitPrice",
  "shopPlatformsPrice",
  "shopRecallPrice",
  "shopRecallChanceGain",
];
export const pickupFields = [
  "pickupDriftOn",
  "pickupDriftMode",
  "pickupDriftRange",
  "pickupDriftSpeedMin",
  "pickupDriftSpeedMax",
  "fieldItemsOn",
  "pickupChance",
  "pickupCap",
  "pickupLife",
  "pickupMinRow",
  "pickupMaxRow",
  "pickupPowerWeight",
  "pickupLightningWeight",
  "pickupRingWeight",
  "pickupSeedWeight",
  "pickupPowerGain",
  "pickupPowerShots",
  "pickupLightningCount",
  "pickupLightningRange",
  "pickupLightningDamage",
  "pickupLightningHpRatio",
  "pickupRingCount",
  "pickupRingDamage",
  "pickupRingHpRatio",
  "pickupRingPierce",
  "pickupRingCap",
  "pickupSeedDamage",
  "pickupSeedHpRatio",
  "pickupSeedDelay",
  "pickupSeedRadius",
];
export const balanceKeys = new Set([
  ...Object.keys(balanceSchema),
  ...stageBalanceKeys,
  "gameMode",
  "xpBase",
  "xpGrowth",
  "xpDrop",
  ...Object.values(skillFields).flat(),
  ...pressureFields,
  ...economyFields,
  ...pickupFields,
]);
export const selectBalance = (c) =>
  Object.fromEntries([...balanceKeys].map((k) => [k, c[k]]));
export const profileKeys = (id) => [
  id + "CurveMode",
  curveProfiles[id].base,
  curveProfiles[id].gain,
  id + "CurvePower",
  id + "CurveMax",
  ...curveProfiles[id].xs.map((_, i) => id + "CurveP" + i),
];
