// Experimental stage mode. Existing saves remain in endless mode.
const field = (group, label, value, min, max, step = 1, when = "下次事件") => ({
  group,
  label,
  value,
  min,
  max,
  step,
  when,
  balanceOnly: true,
});
const bool = (group, label, value) => ({
  group,
  label,
  value,
  type: "boolean",
  when: "下次出刀",
  balanceOnly: true,
});
export const stageSchema = {
  gameMode: {
    group: "游戏模式",
    label: "游戏模式",
    value: "endless",
    type: "select",
    options: { endless: "无尽练习", stages: "闯关战役" },
    when: "重开",
  },
  stageCampaignMode: {
    group: "战役结构",
    label: "关卡路线版本",
    value: "campaign",
    type: "select",
    options: {
      campaign: "30关战役 · 普通关与周期首领",
      demo: "旧版双Boss演示",
    },
    when: "重开",
    balanceOnly: true,
  },
  campaignOverflowLevelOn: {
    group: "战役结构",
    label: "技能满级后继续自然升级",
    value: true,
    type: "boolean",
    when: "下一次升级",
    balanceOnly: true,
  },
  stageSupplyMode: {
    group: "关卡布阵与补压",
    label: "关卡补怪方式",
    value: "adaptive",
    type: "select",
    options: {
      adaptive: "动态压力 · 开局布阵与清屏补充",
      curve: "旧版 · 回合累计曲线",
    },
    when: "下一关",
    balanceOnly: true,
  },
  stagePrepTurns: field("关卡供给", "每关供给回合数", 24, 1, 100, 1, "下一关"),
  stageSpawnCurvePower: field(
    "关卡供给",
    "普通供给增长曲线指数",
    1.5,
    0.25,
    3,
    0.05,
    "下一关",
  ),
  stage1Budget: field(
    "关卡供给",
    "第一关普通敌人总预算",
    68,
    0,
    500,
    1,
    "下一关",
  ),
  stage2Budget: field(
    "关卡供给",
    "第二关普通敌人总预算",
    96,
    0,
    500,
    1,
    "下一关",
  ),
  stage1Hp: field("关卡供给", "第一关初始怪物HP", 10, 1, 5000),
  stage2Hp: field("关卡供给", "第二关初始怪物HP", 30, 1, 5000),
  stage1HpGain: field("关卡供给", "第一关每供给回合HP增长", 0.8, 0, 100, 0.1),
  stage2HpGain: field("关卡供给", "第二关每供给回合HP增长", 1.1, 0, 100, 0.1),
  stageFastChance: field("关卡供给", "关卡快速怪概率", 0.15, 0, 1, 0.01),
  stageBombChance: field("关卡供给", "关卡爆炸怪概率", 0.08, 0, 1, 0.01),
  stageBossHpRatioFactor: field(
    "关卡供给",
    "Boss承受百分比HP伤害系数",
    0.25,
    0,
    2,
    0.05,
  ),
  bossFortressHp: field("堡垒巨兽", "堡垒巨兽HP", 480, 1, 100000),
  bossFortressMoveEvery: field("堡垒巨兽", "堡垒每几回合推进", 2, 1, 20),
  bossFortressAdvance: field("堡垒巨兽", "堡垒每次推进格数", 1, 0, 3, 0.25),
  bossFortressNormalTurns: field("堡垒巨兽", "堡垒普通期回合数", 1, 1, 10),
  bossFortressChargeTurns: field("堡垒巨兽", "堡垒蓄力期回合数", 1, 1, 10),
  bossFortressWeakTurns: field("堡垒巨兽", "堡垒破绽期回合数", 1, 1, 10),
  bossFortressChargeFactor: field(
    "堡垒巨兽",
    "蓄力时承伤倍率",
    0.8,
    0.05,
    3,
    0.05,
  ),
  bossFortressWeakFactor: field(
    "堡垒巨兽",
    "破绽时承伤倍率",
    1.3,
    0.05,
    5,
    0.05,
  ),
  bossFortressXp: field("堡垒巨兽", "堡垒击杀基础经验", 12, 0, 500),
  bossFortressCoins: field("堡垒巨兽", "堡垒击杀金币", 20, 0, 1000),
  bossSummonerHp: field("召唤领主", "召唤领主HP", 550, 1, 100000),
  bossSummonerMoveEvery: field("召唤领主", "领主每几回合推进", 2, 1, 20),
  bossSummonerAdvance: field("召唤领主", "领主每次推进格数", 1, 0, 3, 0.25),
  bossSummonChargeTurns: field("召唤领主", "召唤蓄力回合数", 2, 1, 10),
  bossSummonRestTurns: field("召唤领主", "召唤后恢复回合数", 2, 1, 10),
  bossSummonCount: field("召唤领主", "每批召唤小怪数量", 3, 1, 20),
  bossSummonBudget: field(
    "召唤领主",
    "每关召唤总预算",
    18,
    0,
    200,
    1,
    "下一关",
  ),
  bossSummonCap: field("召唤领主", "同时存活召唤小怪上限", 6, 1, 50),
  bossSummonHp: field("召唤领主", "召唤小怪HP", 18, 1, 5000),
  bossSummonAdvance: field("召唤领主", "召唤小怪每次推进格数", 2, 0, 5, 0.25),
  bossSummonerXp: field("召唤领主", "领主击杀基础经验", 16, 0, 500),
  bossSummonerCoins: field("召唤领主", "领主击杀金币", 30, 0, 1000),
  comboHitOn: bool("连击经验", "启用不同目标连击经验", true),
  comboHitGain: field("连击经验", "每追加命中目标经验加成", 0.02, 0, 1, 0.01),
  comboHitCap: field("连击经验", "命中经验加成上限", 0.2, 0, 3, 0.01),
  comboKillOn: bool("连击经验", "启用同轮连杀经验", true),
  comboKillGain: field("连击经验", "每追加击杀经验加成", 0.08, 0, 1, 0.01),
  comboKillCap: field("连击经验", "连杀经验加成上限", 0.4, 0, 3, 0.01),
  comboFastOn: bool("连击经验", "启用快速连杀经验", true),
  comboFastWindow: field("连击经验", "快速连杀间隔秒数", 1.2, 0.1, 10, 0.1),
  comboFastGain: field("连击经验", "每追加快杀经验加成", 0.05, 0, 1, 0.01),
  comboFastCap: field("连击经验", "快杀经验加成上限", 0.2, 0, 3, 0.01),
  comboMaxMultiplier: field("连击经验", "连击总经验倍率上限", 1.8, 1, 5, 0.05),
};
for (const [group, key, label, value, min, max, step = 1, when = "下一关"] of [
  ["战役结构", "campaignTotal", "战役总关数", 30, 1, 100, 1, "重开"],
  ["战役结构", "campaignBossEvery", "每几关出现首领", 15, 1, 50, 1, "重开"],
  ["战役生命成长", "campaignHpBase", "第一关基础HP", 10, 1, 10000],
  ["战役生命成长", "campaignHpGain", "逐关HP增长系数", 18, 0, 1000, 0.5],
  ["战役生命成长", "campaignHpPower", "逐关HP成长指数", 1.55, 0.25, 3, 0.05],
  [
    "战役生命成长",
    "campaignHpRoundRatio",
    "关内每轮HP增加比例",
    0.01,
    0,
    0.2,
    0.005,
  ],
  ["战役供给成长", "campaignBudgetBase", "第一关怪物总量", 48, 0, 500],
  ["战役供给成长", "campaignBudgetGain", "逐关总量增长系数", 5, 0, 100, 0.5],
  ["战役供给成长", "campaignBudgetPower", "逐关总量成长指数", 1, 0.25, 2, 0.05],
  ["战役供给成长", "campaignOpeningStart", "第一关开局怪物数", 4, 0, 200],
  ["战役供给成长", "campaignOpeningEnd", "末关开局怪物数", 20, 0, 200],
  ["战役供给成长", "campaignTargetStart", "第一关初段目标存量", 6, 0, 200],
  ["战役供给成长", "campaignTargetEnd", "末关初段目标存量", 24, 0, 200],
  ["战役供给成长", "campaignTargetLateGain", "每关后段目标存量追加", 6, 0, 100],
  [
    "战役供给成长",
    "campaignPressurePower",
    "逐关存量与开局成长指数",
    1,
    0.25,
    3,
    0.05,
  ],
  ["战役布阵成长", "campaignOpeningDepthStart", "第一关开局最深行", 4, 1, 16],
  ["战役布阵成长", "campaignOpeningDepthEnd", "末关开局最深行", 7, 1, 16],
  ["战役布阵成长", "campaignSpawnDepthStart", "第一关后续最深入场行", 6, 1, 16],
  ["战役布阵成长", "campaignSpawnDepthEnd", "末关后续最深入场行", 8, 1, 16],
  ["战役布阵成长", "campaignFrontStart", "第一关初段前压概率", 0.1, 0, 1, 0.01],
  ["战役布阵成长", "campaignFrontEnd", "末关初段前压概率", 0.6, 0, 1, 0.01],
  [
    "战役布阵成长",
    "campaignFrontPower",
    "逐关深度与前压成长指数",
    1,
    0.25,
    3,
    0.05,
  ],
  ["战役怪物组成", "campaignFastStart", "第一关快速怪概率", 0.08, 0, 1, 0.01],
  ["战役怪物组成", "campaignFastEnd", "末关快速怪概率", 0.35, 0, 1, 0.01],
  [
    "战役怪物组成",
    "campaignFastPower",
    "逐关快速怪概率成长指数",
    1,
    0.25,
    3,
    0.05,
  ],
  ["战役怪物组成", "campaignBombChance", "战役爆炸怪概率", 0.08, 0, 1, 0.01],
  [
    "战役首领成长",
    "campaignFortressHpFactor",
    "堡垒HP/本关基础HP",
    12,
    1,
    100,
    0.5,
  ],
  [
    "战役首领成长",
    "campaignSummonerHpFactor",
    "召唤领主HP/本关基础HP",
    16,
    1,
    100,
    0.5,
  ],
  [
    "战役首领成长",
    "campaignSummonHpFactor",
    "召唤小怪HP/本关基础HP",
    0.65,
    0.05,
    5,
    0.05,
  ],
])
  stageSchema[key] = field(group, label, value, min, max, step, when);
for (const [key, label, value, min, max, step, when] of [
  ["stage1OpeningCount", "第一关开局怪物数", 4, 0, 200, 1, "下一关"],
  ["stage2OpeningCount", "第二关开局怪物数", 10, 0, 200, 1, "下一关"],
  ["stage1TargetStart", "第一关初段目标存量", 6, 0, 200, 1],
  ["stage1TargetEnd", "第一关后段目标存量", 12, 0, 200, 1],
  ["stage2TargetStart", "第二关初段目标存量", 14, 0, 200, 1],
  ["stage2TargetEnd", "第二关后段目标存量", 22, 0, 200, 1],
  ["stagePressurePower", "目标存量成长曲线指数", 1.2, 0.25, 4, 0.05],
  ["stageRefillRatio", "目标缺口与清屏补充比例", 0.75, 0, 1.5, 0.05],
  ["stageWaveCap", "单次补怪数量上限", 30, 1, 200, 1],
  ["stage1OpeningDepth", "第一关开局最深行", 4, 1, 16, 1, "下一关"],
  ["stage2OpeningDepth", "第二关开局最深行", 6, 1, 16, 1, "下一关"],
  ["stage1SpawnDepth", "第一关后续最深入场行", 6, 1, 16, 1],
  ["stage2SpawnDepth", "第二关后续最深入场行", 7, 1, 16, 1],
  ["stage1FrontChance", "第一关初段前压概率", 0.1, 0, 1, 0.01],
  ["stage2FrontChance", "第二关初段前压概率", 0.35, 0, 1, 0.01],
  ["stageFrontGrowth", "后段前压概率追加值", 0.2, 0, 1, 0.01],
  ["stageFrontRow", "前压区域从第几行开始", 4, 1, 16, 1],
  ["stageEntryReactionTurns", "新怪至少保留几次应对出手", 2, 1, 6, 1],
])
  stageSchema[key] = field(
    "关卡布阵与补压",
    label,
    value,
    min,
    max,
    step,
    when || "下次补怪",
  );
for (const [key, label, value] of [
  ["bossFortressScale", "堡垒相对普通怪大小", 2],
  ["bossSummonerScale", "领主相对快速怪大小", 1.6],
  ["bossSummonScale", "召唤小怪相对大小", 0.65],
])
  stageSchema[key] = {
    ...field("Boss表现", label, value, 0.25, 4, 0.05, "下次生成"),
    balanceOnly: false,
  };
for (const [key, label, value, min, max, step] of [
  ["stageIntroOn", "战场内入关预告", true],
  ["stageIntroDuration", "入关预告停留秒数", 1.2, 0, 5, 0.1],
  ["stageClearDuration", "通关自动续关停留秒数", 1.5, 0, 5, 0.1],
  ["stageBossIntroOn", "首领出场警报", true],
  ["stageBossIntroDuration", "首领警报停留秒数", 1.8, 0, 6, 0.1],
  ["stageTransitionDuration", "界面退场过渡秒数", 0.4, 0, 2, 0.05],
  ["stageResultCountDuration", "结算数字增长秒数", 0.9, 0, 3, 0.1],
  ["stageCelebrationOn", "通关光芒与庆祝动画", true],
  ["stageSoundOn", "入关、首领与通关音效", true],
  ["stageSoundVolume", "关卡提示音相对音量", 0.65, 0, 1, 0.05],
  ["stageMedalKills", "连杀勋章需要单刀击杀数", 5, 2, 50, 1],
  ["stageComboHoldDuration", "连击结束后保留显示秒数", 2, 0, 8, 0.1],
])
  stageSchema[key] = {
    group: "关卡界面与反馈",
    label,
    value,
    ...(typeof value === "boolean" ? { type: "boolean" } : { min, max, step }),
    when:
      key === "stageMedalKills"
        ? "下次结算/预览"
        : ["stageIntroOn", "stageBossIntroOn"].includes(key)
          ? "下次界面（关闭立即）"
          : "立即",
  };
export const stageBalanceKeys = Object.keys(stageSchema).filter(
  (k) => stageSchema[k].balanceOnly,
);
export const stageDefaults = Object.fromEntries(
  Object.entries(stageSchema).map(([k, v]) => [k, v.value]),
);
export const stageConfig = (c) => ({ ...stageDefaults, ...c });
